# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfiles',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='excelfiles',
            name='attendancePercent',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelfiles',
            name='sapID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
