# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170323_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiles',
            name='files',
            field=models.ManyToManyField(blank=True, to='attendance.Files'),
        ),
    ]
