# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_excelfiles_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfiles',
            name='files',
        ),
    ]
