# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_excelfiles_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='sapID',
            field=models.IntegerField(),
        ),
    ]
