# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20170323_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='attendancePercent',
            field=models.IntegerField(),
        ),
    ]
