# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20170323_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='attendancePercent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='sapID',
            field=models.IntegerField(null=True),
        ),
    ]
